apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment


spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 8080